# Generated by Django 6.0 on 2026-08-31 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fix_typo_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoryRecommendedPart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(db_column='subcategory_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommended_parts', to='core.subcategoryproduct')),
            ],
            options={
                'verbose_name': 'Subcategory recommended part',
                'verbose_name_plural': 'Subcategory recommended parts',
                'db_table': 'subcategory_recommended_parts',
                'ordering': ['sort_order', 'id'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('subcategory', 'name'), name='uq_recommended_part_name_per_subcategory')],
            },
        ),
    ]
