# Generated by Django 6.0.3 on 2026-03-25 21:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_first_name', models.CharField(db_column='contact_first_name', max_length=100)),
                ('contact_last_name', models.CharField(db_column='contact_last_name', max_length=100)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='core.client')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='client_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Contact',
                'verbose_name_plural': 'Client Contacts',
                'db_table': 'client_contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quotation_type', models.CharField(choices=[('VENTA', 'Venta'), ('ALQUILER', 'Alquiler'), ('SERVICIO', 'Servicio')], db_column='type', max_length=20)),
                ('money', models.CharField(choices=[('USD', 'USD'), ('PEN', 'PEN')], db_column='money', max_length=5)),
                ('status', models.CharField(choices=[('APROBADA', 'Aprobada'), ('PENDIENTE', 'Pendiente'), ('RECHAZADA', 'Rechazada')], max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.IntegerField(db_column='delivery_time')),
                ('conditions', models.TextField()),
                ('works', models.TextField()),
                ('see_sku', models.BooleanField(db_column='see_sku')),
                ('creation_date', models.DateTimeField(db_column='creation_date', default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(db_column='update_date', default=django.utils.timezone.now)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='core.client')),
                ('payment_methods', models.ForeignKey(db_column='payment_methods_id', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='core.paymentmethods')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'db_table': 'quotation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuotationProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cant', models.IntegerField()),
                ('product_price', models.DecimalField(db_column='product_price', decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='almacen.product')),
                ('quotation', models.ForeignKey(db_column='quotation_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='ventas.quotation')),
            ],
            options={
                'verbose_name': 'Quotation Item',
                'verbose_name_plural': 'Quotation Items',
                'db_table': 'quotation_product',
                'managed': True,
            },
        ),
    ]
