# Generated by Django 6.0.3 on 2026-03-25 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_options'),
        ('core', '0001_initial'),
        ('ventas', '0002_clientcontact_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='clientcontact',
            constraint=models.UniqueConstraint(fields=('company', 'client', 'email'), name='uq_client_contact_email_per_company'),
        ),
    ]
