# Generated by Django 6.0.3 on 2026-03-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_clientcontact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
