# Generated by Django 6.0.3 on 2026-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_quotation_sequence_correlativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotationproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
