# Generated by Django 6.0.1 on 2026-03-30 22:48

from django.db import migrations, models


def backfill_line_snapshot_from_product(apps, schema_editor):
    QuotationProduct = apps.get_model("ventas", "QuotationProduct")
    Product = apps.get_model("almacen", "Product")
    for qp in QuotationProduct.objects.all().iterator():
        try:
            p = Product.objects.get(pk=qp.product_id)
        except Product.DoesNotExist:
            continue
        QuotationProduct.objects.filter(pk=qp.pk).update(
            line_sku=p.sku,
            line_description=p.description,
            line_datasheet=p.datasheet,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0006_alter_clientcontact_id_alter_quotation_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationproduct",
            name="line_datasheet",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="quotationproduct",
            name="line_description",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="quotationproduct",
            name="line_sku",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RunPython(backfill_line_snapshot_from_product, noop_reverse),
    ]
