# Generated by Django 6.0.1 on 2026-03-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_quotation_product_line_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='exchange_rate',
            field=models.DecimalField(blank=True, db_column='exchange_rate', decimal_places=4, max_digits=12, null=True),
        ),
    ]
