# Generated by Django 6.0.3 on 2026-03-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_quotation_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='works',
            field=models.TextField(blank=True, null=True),
        ),
    ]
