# Generated by Django 6.0.3 on 2026-05-11 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_quotation_client_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='rental_quantity',
            field=models.PositiveIntegerField(blank=True, db_column='rental_quantity', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rental_unit',
            field=models.CharField(blank=True, choices=[('DIAS', 'Días'), ('MES', 'Mes')], db_column='rental_unit', max_length=4, null=True),
        ),
    ]
