# Generated by Django 6.0 on 2026-05-15 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_cellphone_consistency'),
        ('core', '0006_fix_typo_columns'),
        ('ventas', '0012_quotation_rental_unit_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_channel', models.CharField(choices=[('META', 'META'), ('GOOGLE_ADS', 'Google Ads'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], db_column='entry_channel', max_length=20, verbose_name='Medio de entrada')),
                ('proforma_type', models.CharField(choices=[('MAQUINARIA', 'Maquinaria'), ('REPUESTOS', 'Repuestos'), ('SERVICIOS', 'Servicios'), ('ALQUILERES', 'Alquileres')], db_column='proforma_type', max_length=20, verbose_name='Tipo de proforma')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('assigned_user', models.ForeignKey(db_column='assigned_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='proforma_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='proforma_requests', to='core.client')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, related_name='proforma_requests', to='accounts.company')),
                ('quotation', models.ForeignKey(blank=True, db_column='quotation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_requests', to='ventas.quotation')),
            ],
            options={
                'verbose_name': 'Proforma Request',
                'verbose_name_plural': 'Proforma Requests',
                'db_table': 'proforma_request',
                'managed': True,
                'indexes': [models.Index(fields=['company_id'], name='proforma_req_company_idx')],
            },
        ),
    ]
