# Generated by Django 6.0 on 2026-05-15 21:15

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_cellphone_consistency'),
        ('core', '0006_fix_typo_columns'),
        ('ventas', '0013_proforma_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proformarequest',
            name='entered_at',
            field=models.DateTimeField(db_column='entered_at', default=django.utils.timezone.now, editable=False, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='proformarequest',
            name='quoted_at',
            field=models.DateTimeField(blank=True, db_column='quoted_at', help_text='Momento en que se vinculó una cotización (primera vez o nuevo vínculo).', null=True, verbose_name='Fecha de cotización'),
        ),
        migrations.AddIndex(
            model_name='proformarequest',
            index=models.Index(fields=['entered_at'], name='proforma_req_entered_idx'),
        ),
    ]
