# Generated by Django 6.0 on 2026-05-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_proforma_request_entered_quoted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformarequest',
            name='status',
            field=models.CharField(choices=[('APROBADA', 'Aprobada'), ('PENDIENTE', 'Pendiente'), ('RECHAZADA', 'Rechazada'), ('SIN_RESPUESTA', 'Sin respuesta')], db_column='status', default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
    ]
