# Generated by Django 6.0 on 2026-08-07 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_delivery_time_text_and_line_warranty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationEmailLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('to_emails', models.TextField(help_text='Lista de destinatarios separados por coma.')),
                ('cc_emails', models.TextField(blank=True, default='')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('quotation', models.ForeignKey(db_column='quotation_id', on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='ventas.quotation')),
                ('sent_by', models.ForeignKey(blank=True, db_column='sent_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_emails_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotation_email_log',
                'ordering': ['-created_at', '-id'],
                'managed': True,
            },
        ),
    ]
