# Generated by Django 6.0 on 2026-08-10 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0022_alter_userprofile_role_servicios'),
        ('core', '0006_fix_typo_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('plate_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('daily_working_hours', models.PositiveIntegerField()),
                ('current_hour_meter', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('OUT_OF_SERVICE', 'Fuera de servicio'), ('DECOMMISSIONED', 'Dada de baja')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.brand')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.client')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'db_table': 'machines',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('company', 'serial_number'), name='uq_machine_serial_per_company')],
            },
        ),
    ]
