# Generated by Django 6.0 on 2026-08-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='voltage',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
