# Generated by Django 6.0 on 2026-08-31 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_starter_type_vfd_to_vsd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('EVALUATION', 'Evaluación'), ('SERVICE', 'Servicio')], max_length=20)),
                ('intervention_date', models.DateField()),
                ('hour_meter', models.PositiveIntegerField(blank=True, null=True)),
                ('current_condition', models.CharField(choices=[('OPERATIONAL', 'Operativo'), ('INOPERATIVE', 'Inoperativo')], max_length=20)),
                ('background', models.TextField(blank=True, default='')),
                ('conclusions', models.TextField(blank=True, default='')),
                ('recommendations', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.PROTECT, related_name='machine_reports', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(db_column='machine_id', on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='servicios.machine')),
                ('origin_report', models.ForeignKey(blank=True, db_column='origin_report_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_reports', to='servicios.machinereport')),
            ],
            options={
                'verbose_name': 'Machine report',
                'verbose_name_plural': 'Machine reports',
                'db_table': 'machine_reports',
                'ordering': ['-intervention_date', '-id'],
                'managed': True,
            },
        ),
    ]
