# Generated by Django 6.0 on 2026-08-31 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recommended_parts_categories_work_checks'),
        ('servicios', '0005_machine_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.categoryproduct'),
        ),
        migrations.AddField(
            model_name='machine',
            name='subcategory',
            field=models.ForeignKey(blank=True, db_column='subcategory_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.subcategoryproduct'),
        ),
        migrations.AddField(
            model_name='machinereport',
            name='work_performed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='MachineReportPartCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(choices=[('OK', 'Buen estado'), ('REPLACE', 'Reemplazar'), ('CLEAN', 'Solo limpiar')], max_length=20)),
                ('part_number', models.CharField(blank=True, default='', max_length=250)),
                ('notes', models.TextField(blank=True, default='')),
                ('recommended_part', models.ForeignKey(db_column='recommended_part_id', on_delete=django.db.models.deletion.PROTECT, related_name='report_checks', to='core.subcategoryrecommendedpart')),
                ('report', models.ForeignKey(db_column='report_id', on_delete=django.db.models.deletion.CASCADE, related_name='part_checks', to='servicios.machinereport')),
            ],
            options={
                'verbose_name': 'Machine report part check',
                'verbose_name_plural': 'Machine report part checks',
                'db_table': 'machine_report_part_checks',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('report', 'recommended_part'), name='uq_report_recommended_part')],
            },
        ),
    ]
