# Generated by Django 6.0 on 2026-08-31 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_recommended_parts_categories_work_checks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineReportPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_url', models.URLField(max_length=500)),
                ('label', models.CharField(choices=[('BEFORE', 'Before'), ('DURING', 'During'), ('AFTER', 'After')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(db_column='report_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='servicios.machinereport')),
            ],
            options={
                'verbose_name': 'Machine report photo',
                'verbose_name_plural': 'Machine report photos',
                'db_table': 'machine_report_photos',
                'ordering': ['sort_order', 'id'],
                'managed': True,
            },
        ),
    ]
