# Generated by Django 6.0 on 2026-08-31 17:39

import django.db.models.deletion
from django.db import migrations, models


def backfill_correlativos(apps, schema_editor):
    MachineReport = apps.get_model("servicios", "MachineReport")
    ReportSequence = apps.get_model("servicios", "ReportSequence")
    prefix_map = {"EVALUATION": "EVA", "SERVICE": "SRV"}
    for report in MachineReport.objects.select_related("machine").order_by("id"):
        if (report.correlativo or "").strip():
            continue
        company_id = report.machine.company_id
        prefix = prefix_map.get(report.type, "RPT")
        seq, _ = ReportSequence.objects.get_or_create(
            company_id=company_id,
            prefix=prefix,
            defaults={"last_number": 0},
        )
        seq.last_number += 1
        seq.save(update_fields=["last_number"])
        report.correlativo = f"{company_id}-{prefix}-{seq.last_number:06d}"
        report.save(update_fields=["correlativo"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_userprofile_role_servicios"),
        ("servicios", "0007_report_photos"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSequence",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("prefix", models.CharField(max_length=10)),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_sequences",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "db_table": "report_sequence",
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "prefix"),
                        name="uq_report_sequence_company_prefix",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="machinereport",
            name="correlativo",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.RunPython(backfill_correlativos, noop_reverse),
        migrations.AlterField(
            model_name="machinereport",
            name="correlativo",
            field=models.CharField(blank=True, default="", max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name="ReportElectricalEvaluation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nominal_voltage",
                    models.CharField(
                        blank=True,
                        choices=[("220V", "220 V"), ("380V", "380 V"), ("440V", "440 V")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "actual_voltage_l1_l2",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "actual_voltage_l2_l3",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "actual_voltage_l3_l1",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "main_motor_current_l1",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "main_motor_current_l2",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "main_motor_current_l3",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "fan_motor_current_l1",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "fan_motor_current_l2",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "fan_motor_current_l3",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "starter_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIRECT", "Directo"),
                            ("STAR_DELTA", "Estrella-triángulo"),
                            ("VSD", "VSD"),
                            ("SOFT", "SOFT"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("starter_brand", models.CharField(blank=True, default="", max_length=100)),
                (
                    "control_voltage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("110_VAC", "110 VAC"),
                            ("220_VAC", "220 VAC"),
                            ("24_VDC", "24 VDC"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("grounding", models.CharField(blank=True, default="", max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.OneToOneField(
                        db_column="report_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="electrical_evaluation",
                        to="servicios.machinereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report electrical evaluation",
                "verbose_name_plural": "Report electrical evaluations",
                "db_table": "report_electrical_evaluation",
                "managed": True,
            },
        ),
    ]
