# Generated by Cursor on 2026-03-25

from django.db import migrations
from django.db.utils import OperationalError


def seed_companies(apps, schema_editor):
    Company = apps.get_model("accounts", "Company")

    # En SQLite (dev) aseguramos que la tabla exista.
    try:
        existing_tables = schema_editor.connection.introspection.table_names()
        if "company" not in existing_tables:
            schema_editor.create_model(Company)
    except OperationalError:
        # Si falla por cualquier motivo (ej. ya existe), seguimos a seed.
        pass

    Company.objects.update_or_create(id=1, defaults={"name": "CDP"})
    Company.objects.update_or_create(id=2, defaults={"name": "LEOS"})


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_companies, migrations.RunPython.noop),
    ]

