# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_company_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="quotation_prefix",
            field=models.CharField(
                blank=True,
                db_column="quotation_prefix",
                default="",
                max_length=10,
            ),
        ),
    ]
