# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_quotation_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ALMACEN", "Almacén"),
                    ("VENTAS", "Ventas"),
                    ("LOGISTICA", "Logística"),
                    ("ADMIN", "Administrador"),
                ],
                db_column="role",
                default="VENTAS",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
