# Generated by Django 6.0.3 on 2026-03-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_superuser_profile_role_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='quotation_prefix',
            field=models.CharField(blank=True, db_column='quotation_prefix', default='', help_text='Letras usadas en el correlativo, ej. GER → GER-001052', max_length=10, verbose_name='Prefijo cotizaciones (iniciales)'),
        ),
    ]
