# Generated by Django 6.0.3 on 2026-03-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='celular',
            field=models.CharField(blank=True, db_column='celular', default='', max_length=20, verbose_name='Celular'),
        ),
    ]
