# Generated by Django 6.0.3 on 2026-03-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_userprofile_celular"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="celular",
            new_name="cellphone",
        ),
    ]
