# Generated by Django 6.0.1 on 2026-03-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_company_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_accounts',
            field=models.TextField(blank=True, default='', help_text='Datos de cuentas bancarias (texto libre).', verbose_name='Bank accounts'),
        ),
    ]
