# Generated by Django 6.0 on 2026-08-07 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_cellphone_consistency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmailSettings',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_settings', serialize=False, to='accounts.company')),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password_encrypted', models.TextField(blank=True, default='')),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company email settings',
                'verbose_name_plural': 'Company email settings',
                'db_table': 'company_email_settings',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_display_name',
            field=models.CharField(blank=True, default='', help_text='Si está vacío se usa el nombre del usuario.', max_length=150, verbose_name='Nombre visible en correos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reply_to_email',
            field=models.EmailField(blank=True, default='', help_text='Si está vacío se usa user.email.', max_length=254, verbose_name='Reply-To al enviar cotizaciones'),
        ),
    ]
