# Generated by Django 6.0.3 on 2026-08-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_company_email_settings_and_quotation_email_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemailsettings',
            name='default_cc',
            field=models.JSONField(blank=True, default=list, help_text='Emails en copia por defecto al enviar cotizaciones (lista).'),
        ),
    ]
