# Generated by Django 6.0.3 on 2026-08-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_company_email_default_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signature_url',
            field=models.URLField(blank=True, default='', help_text='Imagen de firma del usuario en Cloudinary.', max_length=500, verbose_name='URL de firma (Cloudinary)'),
        ),
    ]
