# Generated by Django 6.0.3 on 2026-03-25 21:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('ubication', models.CharField(max_length=250)),
                ('creation_date', models.DateTimeField(db_column='creation_date', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'warehouse_product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('datasheet', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_price_without_operator', models.DecimalField(blank=True, db_column='rental_price_without_operator', decimal_places=2, max_digits=10, null=True)),
                ('rental_price_with_operator', models.DecimalField(blank=True, db_column='rental_price_with_operator', decimal_places=2, max_digits=10, null=True)),
                ('warrannty', models.CharField(db_column='warrannty', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_column='status', max_length=20)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('gross_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField(db_column='creation_date', default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(db_column='update_date', default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.brand')),
                ('subcategory', models.ForeignKey(db_column='subcategory_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.subcategoryproduct')),
                ('type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.typeproduct')),
                ('unit_measurement', models.ForeignKey(db_column='unit_measurement_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.unitmeasurement')),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('primary', models.BooleanField(db_column='primary')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='images', to='almacen.product')),
            ],
            options={
                'db_table': 'product_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('money', models.CharField(choices=[('USD', 'USD'), ('PEN', 'PEN')], db_column='money', max_length=5)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incoterm', models.CharField(max_length=3)),
                ('creation_date', models.DateTimeField(db_column='creation_date', default=django.utils.timezone.now)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='almacen.product')),
                ('supplier', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.supplier')),
            ],
            options={
                'db_table': 'product_supplier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('supplier', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='core.supplier')),
            ],
            options={
                'db_table': 'warehouse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WarehouseMovements',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movement_type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], db_column='type', max_length=20)),
                ('observation', models.IntegerField()),
                ('creation_date', models.DateTimeField(db_column='creation_date', default=django.utils.timezone.now)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_movements', to='almacen.product')),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='almacen.warehouse')),
            ],
            options={
                'db_table': 'warehouse_movements',
                'managed': True,
            },
        ),
    ]
