# Generated by Django 6.0.3 on 2026-03-25 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='quotation',
            field=models.ForeignKey(db_column='quotation_id', on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_products', to='ventas.quotation'),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_products', to='almacen.warehouse'),
        ),
    ]
