# Generated by Django 6.0.3 on 2026-03-26 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_initial'),
        ('ventas', '0004_clientcontact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_stocks', to='almacen.product'),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='quotation',
            field=models.ForeignKey(blank=True, db_column='quotation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_products', to='ventas.quotation'),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='warehouseproduct',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='uq_warehouse_product_stock'),
        ),
    ]
