# Generated by Django 6.0.3 on 2026-03-27 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_warehouseproduct_product_alter_warehouseproduct_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='quotation',
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_stocks', to='almacen.product'),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
