# Generated by Django 6.0 on 2026-04-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_alter_product_id_alter_productimage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datasheet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warrannty',
            field=models.CharField(blank=True, db_column='warrannty', max_length=20, null=True),
        ),
    ]
